#!/bin/bash
#
# ------------------------------------------------------------
#  install.sh
#
#  Installer / Updater for asl3-cleanup-recordings
#  Author: Larry K. Aycock (N6LKA)
#
#  Usage:
#     bash <(curl -s https://raw.githubusercontent.com/N6LKA/asl3-cleanup-recordings/main/install.sh)
#
# ------------------------------------------------------------

BASE_URL="https://raw.githubusercontent.com/N6LKA/asl3-cleanup-recordings/main"
INSTALL_DIR="/etc/asterisk/scripts/cleanup-recordings"
SCRIPT_FILE="$INSTALL_DIR/cleanup-recordings.sh"
CONF_FILE="$INSTALL_DIR/cleanup-recordings.conf"
CONF_EXAMPLE="$INSTALL_DIR/cleanup-recordings.conf.example"

# ====== ROOT CHECK ======
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: This script must be run as root (sudo)."
    exit 1
fi

echo "============================================"
echo " asl3-cleanup-recordings Installer"
echo " by Larry K. Aycock (N6LKA)"
echo "============================================"

# ====== DETECT EXISTING INSTALL ======
IS_UPDATE=false
if [ -f "$SCRIPT_FILE" ]; then
    IS_UPDATE=true
    echo "Existing installation detected. Updating..."
else
    echo "Fresh installation..."
fi

# ====== CREATE DIRECTORY ======
mkdir -p "$INSTALL_DIR"

# ====== DOWNLOAD MAIN SCRIPT ======
echo "Downloading cleanup-recordings.sh..."
curl -fsSL "$BASE_URL/cleanup-recordings.sh" -o "$SCRIPT_FILE"
chmod +x "$SCRIPT_FILE"

# ====== DOWNLOAD CONF EXAMPLE ======
echo "Downloading cleanup-recordings.conf.example..."
curl -fsSL "$BASE_URL/cleanup-recordings.conf.example" -o "$CONF_EXAMPLE"

# ====== CREATE CONF IF NOT EXISTS ======
if [ ! -f "$CONF_FILE" ]; then
    echo ""
    echo "No configuration file found. Let's set it up."
    echo ""

    read -p "Enter your AllStar node number: " NODE
    while [ -z "$NODE" ]; do
        read -p "Node number is required. Enter your AllStar node number: " NODE
    done

    read -p "Number of days to keep recordings [14]: " input_days
    DAYS_TO_KEEP="${input_days:-14}"

    read -p "Recording directory [/recordings/${NODE}]: " input_dir
    TARGET_DIR="${input_dir:-/recordings/${NODE}}"

    echo ""
    echo "Cron schedule for automatic cleanup."
    echo "  Examples:"
    echo "    0 3 * * 0  = Every Sunday at 3:00 AM (default)"
    echo "    0 3 * * *  = Every day at 3:00 AM"
    echo "    0 3 1 * *  = First of every month at 3:00 AM"
    read -p "Enter cron schedule [0 3 * * 0]: " input_cron
    CRON_SCHEDULE="${input_cron:-0 3 * * 0}"

    cat > "$CONF_FILE" <<EOF
# ============================================================
#  cleanup-recordings.conf
#  Generated by install.sh on $(date)
#  Edit this file to customize behavior.
# ============================================================

NODE="$NODE"
DAYS_TO_KEEP=$DAYS_TO_KEEP
TARGET_DIR="/recordings/\${NODE}"
CRON_SCHEDULE="$CRON_SCHEDULE"
EOF

    echo "Configuration file created: $CONF_FILE"
else
    echo "Existing config preserved: $CONF_FILE"
fi

# ====== CHECK FOR MISSING CONFIG VARS (for updates) ======
append_var() {
    local var="$1"
    local default="$2"
    if ! grep -q "^${var}=" "$CONF_FILE"; then
        echo "" >> "$CONF_FILE"
        echo "# Added by installer on $(date)" >> "$CONF_FILE"
        echo "${var}=\"${default}\"" >> "$CONF_FILE"
        echo "Added missing config variable: $var"
    fi
}

append_var "CRON_SCHEDULE" "0 3 * * 0"

# ====== LOAD CONF TO GET CRON_SCHEDULE ======
source "$CONF_FILE"

# ====== INSTALL CRON JOB ======
echo "Installing cron job..."

# Remove any existing entries (handles migration from old /etc/asterisk/local/ path too)
crontab -l 2>/dev/null | grep -v "cleanup.recordings\|cleanup_recordings" | crontab -

# Add new entry with comment
(crontab -l 2>/dev/null; echo ""; echo "# Cleanup old AllStar recording files on node $NODE"; echo "$CRON_SCHEDULE $SCRIPT_FILE >/dev/null 2>&1") | crontab -

echo "Cron job installed: $CRON_SCHEDULE"

# ====== SET PERMISSIONS ======
chown -R root:asterisk "$INSTALL_DIR"

# ====== DONE ======
echo ""
echo "============================================"
if [ "$IS_UPDATE" = true ]; then
    echo " Update complete!"
else
    echo " Installation complete!"
fi
echo ""
echo " Script:    $SCRIPT_FILE"
echo " Config:    $CONF_FILE"
echo " Schedule:  $CRON_SCHEDULE"
echo ""
echo " To run manually:      $SCRIPT_FILE"
echo " To test (no delete):  $SCRIPT_FILE test"
echo " To edit config:       nano $CONF_FILE"
echo " To re-run installer:  bash <(curl -s $BASE_URL/install.sh)"
echo "============================================"
